#pragma once


#define RT_SUCCESS 0
#define RT_WRONG_ARGUMENT -1
#define RT_LIBRARY_LOAD_FAIL -2
#define RT_SOCKETOPT_FAILURE -4
#define RT_UNDEFINED_MODE_STATE -3
#define RT_CANNOT_BIND_TCP_SOCKET -5
#define RT_CANNOT_BIND_UDP_SOCKET -6